local checkbox = require("lore.checkbox")

local function buf_with(line)
  vim.cmd.enew()
  vim.api.nvim_buf_set_lines(0, 0, -1, false, { line })
  vim.api.nvim_win_set_cursor(0, { 1, 0 })
end

local function line()
  return vim.api.nvim_get_current_line()
end

describe("lore.checkbox", function()
  describe("cycle", function()
    it("advances todo to in-progress", function()
      buf_with("- [ ] task")
      checkbox.cycle()
      assert.equals("- [/] task", line())
    end)

    it("advances in-progress to done", function()
      buf_with("- [/] task")
      checkbox.cycle()
      assert.equals("- [x] task", line())
    end)

    it("wraps done back to todo", function()
      buf_with("- [x] task")
      checkbox.cycle()
      assert.equals("- [ ] task", line())
    end)

    it("returns blocked to todo (asserted states are not cycle steps)", function()
      buf_with("- [!] task")
      checkbox.cycle()
      assert.equals("- [ ] task", line())
    end)

    it("promotes a plain bullet to a todo", function()
      buf_with("- just an item")
      checkbox.cycle()
      assert.equals("- [ ] just an item", line())
    end)

    it("promotes an ordered item", function()
      buf_with("3. step three")
      checkbox.cycle()
      assert.equals("3. [ ] step three", line())
    end)

    it("preserves indentation and star bullets", function()
      buf_with("  * [ ] nested")
      checkbox.cycle()
      assert.equals("  * [/] nested", line())
    end)

    it("leaves non-list lines alone", function()
      buf_with("plain prose here")
      checkbox.cycle()
      assert.equals("plain prose here", line())
    end)
  end)

  describe("set", function()
    it("asserts blocked", function()
      buf_with("- [ ] waiting on infra")
      checkbox.set("!")
      assert.equals("- [!] waiting on infra", line())
    end)

    it("rejects the retired dropped state", function()
      buf_with("- [/] task")
      assert.error_matches(function()
        checkbox.set("-")
      end, "unknown checkbox state")
    end)

    it("promotes a plain bullet with the given state", function()
      buf_with("- someday maybe")
      checkbox.set("!")
      assert.equals("- [!] someday maybe", line())
    end)

    it("rejects unknown states", function()
      buf_with("- [ ] task")
      assert.error_matches(function()
        checkbox.set("?")
      end, "unknown checkbox state")
    end)
  end)
end)
