local preferences = require("lore.preferences")
local vaults = require("lore.vaults")
local git = require("lore.git")

describe("lore.git", function()
  local prefs_dir, vault_dir

  local function log_lines()
    local result = vim.system({ "git", "log", "--format=%s" }, { cwd = vault_dir }):wait()
    return vim.split(result.stdout or "", "\n", { trimempty = true })
  end

  before_each(function()
    prefs_dir = vim.fn.tempname()
    vault_dir = vim.fn.tempname()
    preferences.set_directory(prefs_dir)
    git.reset()
    vaults.add("personal", vault_dir)
  end)

  after_each(function()
    preferences.reset_directory()
    vim.fn.delete(prefs_dir, "rf")
    vim.fn.delete(vault_dir, "rf")
  end)

  describe("commit", function()
    it("commits pending changes with a timestamp message", function()
      assert.is_true(git.commit(vault_dir))
      local log = log_lines()
      assert.equals(1, #log)
      assert.matches("^auto: %d%d%d%d%-%d%d%-%d%d", log[1])
    end)

    it("does nothing when clean", function()
      git.commit(vault_dir)
      assert.is_false(git.commit(vault_dir))
      assert.equals(1, #log_lines())
    end)

    it("does nothing for a non-repo path", function()
      local plain = vim.fn.tempname()
      vim.fn.mkdir(plain, "p")
      assert.is_false(git.commit(plain))
      vim.fn.delete(plain, "rf")
    end)
  end)

  describe("commit_all", function()
    it("commits registered vaults and debounces repeats", function()
      git.commit_all()
      assert.equals(1, #log_lines())
      vim.fn.writefile({ "new thought" }, vault_dir .. "/inbox.md")
      git.commit_all()
      assert.equals(1, #log_lines(), "second commit inside the debounce window")
    end)

    it("force bypasses the debounce (the on-quit backstop)", function()
      git.commit_all()
      vim.fn.writefile({ "new thought" }, vault_dir .. "/inbox.md")
      git.commit_all({ force = true })
      assert.equals(2, #log_lines())
    end)
  end)

  describe("checkpoint", function()
    it("writes unsaved buffers so the commit captures the screen", function()
      vim.cmd.edit(vaults.active().path .. "/inbox.md")
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "typed but never :w'd" })
      git.checkpoint()
      assert.same({ "typed but never :w'd" }, vim.fn.readfile(vault_dir .. "/inbox.md"))
      local result = vim.system({ "git", "show", "HEAD:inbox.md" }, { cwd = vault_dir }):wait()
      assert.matches("typed but never", result.stdout)
      vim.cmd("bwipeout!")
    end)
  end)
end)
