local preferences = require("lore.preferences")
local vaults = require("lore.vaults")
local links = require("lore.links")

describe("lore.links", function()
  local prefs_dir, vault_dir

  before_each(function()
    prefs_dir = vim.fn.tempname()
    vault_dir = vim.fn.tempname()
    preferences.set_directory(prefs_dir)
    vaults.add("personal", vault_dir)
  end)

  after_each(function()
    preferences.reset_directory()
    vim.fn.delete(prefs_dir, "rf")
    vim.fn.delete(vault_dir, "rf")
  end)

  describe("resolve", function()
    it("roots /-relative targets at the vault", function()
      assert.equals(vaults.active().path .. "/projects/x.md", links.resolve("/projects/x.md"))
    end)

    it("leaves relative targets alone", function()
      assert.equals("sibling.md", links.resolve("sibling.md"))
    end)
  end)

  describe("target_at_cursor", function()
    local function at(line, col)
      vim.cmd.enew()
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { line })
      vim.api.nvim_win_set_cursor(0, { 1, col - 1 })
      return links.target_at_cursor()
    end

    it("finds the target with the cursor on the link text", function()
      assert.equals("/a.md", at("see [alpha](/a.md) here", 7))
    end)

    it("finds the target with the cursor on the target itself", function()
      assert.equals("/a.md", at("see [alpha](/a.md) here", 14))
    end)

    it("picks the link containing the cursor among several", function()
      assert.equals("/b.md", at("[a](/a.md) and [b](/b.md)", 17))
    end)

    it("is nil off-link", function()
      assert.is_nil(at("see [alpha](/a.md) here", 2))
    end)
  end)

  describe("follow", function()
    it("opens an existing vault-relative target", function()
      vim.fn.mkdir(vault_dir .. "/projects", "p")
      vim.fn.writefile({ "hi" }, vault_dir .. "/projects/x.md")
      vim.cmd.edit(vault_dir .. "/todo.md")
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "[x](/projects/x.md)" })
      vim.api.nvim_win_set_cursor(0, { 1, 1 })
      links.follow()
      assert.equals(vaults.active().path .. "/projects/x.md", vim.api.nvim_buf_get_name(0))
    end)

    it("creates a missing target (directories included) and opens it", function()
      vim.cmd.edit(vault_dir .. "/todo.md")
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "[new](/ideas/brand_new.md)" })
      vim.api.nvim_win_set_cursor(0, { 1, 1 })
      links.follow()
      assert.equals(vaults.active().path .. "/ideas/brand_new.md", vim.api.nvim_buf_get_name(0))
      assert.equals(1, vim.fn.filereadable(vault_dir .. "/ideas/brand_new.md"))
    end)

    it("does not create from a bare prose word", function()
      vim.cmd.edit(vault_dir .. "/todo.md")
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "just the word banana here" })
      vim.api.nvim_win_set_cursor(0, { 1, 10 }) -- on "banana"
      local before = vim.api.nvim_buf_get_name(0)
      links.follow()
      assert.equals(before, vim.api.nvim_buf_get_name(0), "buffer must not change")
      assert.equals(0, vim.fn.filereadable(vault_dir .. "/banana"), "no junk file")
    end)

    it("still opens an existing file via the bare fallback", function()
      vim.fn.writefile({ "x" }, vault_dir .. "/inbox.md")
      vim.cmd.edit(vault_dir .. "/todo.md")
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "see inbox.md for context" })
      vim.api.nvim_win_set_cursor(0, { 1, 5 })
      links.follow()
      assert.equals(vaults.active().path .. "/inbox.md", vim.api.nvim_buf_get_name(0))
    end)

    it("resolves relative targets against the buffer's directory", function()
      vim.fn.mkdir(vault_dir .. "/projects", "p")
      vim.fn.writefile({}, vault_dir .. "/projects/other.md")
      vim.cmd.edit(vault_dir .. "/projects/x.md")
      vim.api.nvim_buf_set_lines(0, 0, -1, false, { "[o](other.md)" })
      vim.api.nvim_win_set_cursor(0, { 1, 1 })
      links.follow()
      assert.equals(vaults.active().path .. "/projects/other.md", vim.api.nvim_buf_get_name(0))
    end)
  end)
end)
