-- Full-stack: real commands, real filesystem, real registry.
require("config.commands")

local preferences = require("lore.preferences")

describe("Lore vault commands", function()
  local prefs_dir, vault_dir

  before_each(function()
    prefs_dir = vim.fn.tempname()
    vault_dir = vim.fn.tempname()
    preferences.set_directory(prefs_dir)
  end)

  after_each(function()
    preferences.reset_directory()
    vim.fn.delete(prefs_dir, "rf")
    vim.fn.delete(vault_dir, "rf")
  end)

  it("LoreVaultAdd registers, scaffolds, and opens the first vault", function()
    vim.cmd(("LoreVaultAdd personal %s"):format(vault_dir))
    assert.equals(vim.uv.fs_realpath(vault_dir), preferences.get("vaults").personal)
    assert.equals(1, vim.fn.filereadable(vault_dir .. "/todo.md"))
    assert.equals("todo.md", vim.fn.fnamemodify(vim.api.nvim_buf_get_name(0), ":t"))
  end)

  it("LoreVaultSwitch changes vault and opens its todo.md", function()
    local other = vim.fn.tempname()
    vim.cmd(("LoreVaultAdd personal %s"):format(vault_dir))
    vim.cmd(("LoreVaultAdd work %s"):format(other))
    vim.cmd("LoreVaultSwitch work")
    assert.equals("work", preferences.get("active_vault"))
    assert.equals(preferences.get("vaults").work, vim.fn.getcwd())
    vim.fn.delete(other, "rf")
  end)

  it("LoreVaultSwitch completes registered names", function()
    vim.cmd(("LoreVaultAdd personal %s"):format(vault_dir))
    local completions = vim.fn.getcompletion("LoreVaultSwitch ", "cmdline")
    assert.same({ "personal" }, completions)
  end)

  it("LoreNewPage defaults to notes/ and honors a folder/ first arg", function()
    vim.cmd(("LoreVaultAdd personal %s"):format(vault_dir))
    vim.cmd("LoreNewPage Some Thought")
    assert.equals(1, vim.fn.filereadable(vault_dir .. "/notes/some_thought.md"))
    vim.cmd("LoreNewPage ideas/ Blog Seed")
    assert.equals(1, vim.fn.filereadable(vault_dir .. "/ideas/blog_seed.md"))
    assert.equals("blog_seed.md", vim.fn.fnamemodify(vim.api.nvim_buf_get_name(0), ":t"))
  end)

  it("LoreInbox with arguments appends to the active vault's inbox", function()
    vim.cmd(("LoreVaultAdd personal %s"):format(vault_dir))
    vim.cmd("LoreInbox remember the milk")
    assert.same({ "remember the milk" }, vim.fn.readfile(vault_dir .. "/inbox.md"))
  end)

  it("LoreTodoAdd appends a fresh todo; a range moves the selection", function()
    vim.cmd(("LoreVaultAdd personal %s"):format(vault_dir))
    vim.cmd("LoreTodoAdd call sarah about headcount")
    assert.same({ "- [ ] call sarah about headcount" }, vim.fn.readfile(vault_dir .. "/todo.md"))
    vim.cmd.enew()
    vim.api.nvim_buf_set_lines(0, 0, -1, false, { "keep this", "move this", "  and this" })
    vim.cmd("2,3LoreTodoAdd")
    assert.same({ "keep this" }, vim.api.nvim_buf_get_lines(0, 0, -1, false))
    assert.same(
      { "- [ ] call sarah about headcount", "- [ ] move this and this" },
      vim.fn.readfile(vault_dir .. "/todo.md")
    )
  end)

  it("LoreInbox with a range moves the lines verbatim", function()
    vim.cmd(("LoreVaultAdd personal %s"):format(vault_dir))
    vim.cmd.enew()
    vim.api.nvim_buf_set_lines(0, 0, -1, false, { "stays", "stray thought" })
    vim.cmd("2LoreInbox")
    assert.same({ "stays" }, vim.api.nvim_buf_get_lines(0, 0, -1, false))
    assert.same({ "stray thought" }, vim.fn.readfile(vault_dir .. "/inbox.md"))
  end)

  it("LoreOpenTodo and LoreOpenInbox jump to the fixture files", function()
    vim.cmd(("LoreVaultAdd personal %s"):format(vault_dir))
    vim.cmd("LoreOpenInbox")
    assert.equals("inbox.md", vim.fn.fnamemodify(vim.api.nvim_buf_get_name(0), ":t"))
    vim.cmd("LoreOpenTodo")
    assert.equals("todo.md", vim.fn.fnamemodify(vim.api.nvim_buf_get_name(0), ":t"))
  end)

  it("LoreBindNew persists and binds a folder alias", function()
    vim.cmd("LoreBindNew r references")
    assert.equals("references", preferences.get("new_page_bindings").r)
    assert.matches("LoreNewPage references/", vim.fn.maparg("<leader>nr", "n"))
  end)

  it("LoreBindNew refuses reserved letters", function()
    local ok, err = pcall(vim.cmd, "LoreBindNew m elsewhere")
    assert.is_false(ok)
    assert.matches("reserved", err)
    assert.is_nil((preferences.get("new_page_bindings") or {}).m)
  end)

  it("surfaces errors as clean messages, not tracebacks", function()
    -- headless, an error-level notify escalates through vim.cmd; assert the
    -- message is the domain error, stripped of file:line noise
    local ok, err = pcall(vim.cmd, "LoreVaultSwitch nope")
    assert.is_false(ok)
    assert.matches('unknown vault "nope"', err)
    assert.is_nil(err:match("vaults%.lua"))
  end)
end)
